apps/swirl-docs/src/lib/navigation/src/pathResolver.ts
apps/swirl-docs/src/pages/api/tokens/v0/utils.ts

- [Ticket](https://flipapp.myjetbrains.com/youtrack/agiles/115-52/current?issue=APP-12264)
summary:
- changed loading function to use node modules instead of monorepo package structure

APP-12264: API is not callable in Docker Image

---

packages/swirl-components/src/docs/02-contributions/01-get-started.stories.mdx

In the storybook documentation is an incorrect GitHub URL to the repository.

Fix wrong GitHub url in storybook

---

.changeset/thick-coats-speak.md
packages/swirl-components/package.json
packages/swirl-components/src/components/swirl-heading/swirl-heading.css
packages/swirl-components/src/components/swirl-heading/swirl-heading.spec.tsx
packages/swirl-components/src/components/swirl-heading/swirl-heading.tsx

- [Ticket](https://github.com/getflip/swirl/issues/445)

#445 replace heading balancing with native css text wrap

---

apps/swirl-docs/src/documents/tokens/color.mdx
apps/swirl-docs/src/lib/tokens/src/colorTokens.ts
apps/swirl-docs/src/lib/tokens/src/token.model.ts
apps/swirl-docs/src/scripts/build-search.ts
packages/swirl-tokens/dart/lib/styles.dark.dart
packages/swirl-tokens/dart/lib/styles.light.dart

Additions:
- Added a new heading "Text"
- Added a new section `<ColorTokens colorCategory="text" />` under the "Text" heading
- Added a new heading "Icon"
- Added a new section `<ColorTokens colorCategory="icon" />` under the "Icon" heading
Modifications:
- Modified the heading "Text" from "Text" to "Focus"
- Modified the section `<ColorTokens colorCategory="text" />` to `<ColorTokens colorCategory="focus" />`
- Modified the heading "Icon" from "Icon" to "Decorative"
- Modified the section `<ColorTokens colorCategory="icon" />` to `<ColorTokens colorCategory="decorative" />`
Additions:
- Added type `ColorTokenGroup` to define the structure of the color tokens collection
- Added function `getColorTokens` to retrieve the color tokens from the codebase
- Added function `getColorCategory` to …

App 19571 new color tokens get weirdly organized on getflip.dev

---

.changeset/shy-apples-attack.md
packages/swirl-components/src/components/swirl-date-input/swirl-date-input.spec.tsx
packages/swirl-components/src/components/swirl-date-input/swirl-date-input.tsx

Relying on the focus event caused some problems on some mobile devices, mainly because it would still keep the focus on the input when we opened the datepicker, which would open the native keyboard on top of the datepicker...
With this approach, we lose the ability to open the datepicker when navigating with the keyboard Tab key, but in fact it was a bit of an anti-patern to open the datepicker when navigating with the keyboard, as we could still do it by hitting Enter on the trigger button.
- [Ticket](#)
- [Design](#)

fix(components): Use click event instead of focus event in swirl-date-input

---

.changeset/beige-sloths-design.md
packages/swirl-components/src/components/swirl-modal/swirl-modal.css

- [Ticket](#)
- [Design](#)
The custom_footer and controls padding is differing from the Figma files, and therefore not aligned with the most recent design.
| Before | After |
|--------|--------|
| <img width="422" alt="Screenshot 2024-05-17 at 14 31 24" src="https://github.com/getflip/swirl/assets/2084270/fc7ed577-0e9f-4da5-a329-da850117a55f"> | <img width="403" alt="Screenshot 2024-05-17 at 14 37 00" src="https://github.com/getflip/swirl/assets/2084270/8c10b6a4-7888-47be-a913-6f925d2e4c07"> |

Fix SwirlModal footer padding on small devices

---

.changeset/khaki-ghosts-film.md
packages/swirl-components/src/components/swirl-file-viewer/viewers/swirl-file-viewer-pdf/swirl-file-viewer-pdf.tsx

- [BSW-118: SwirlFileViewer shows wrong page number](https://linear.app/flip/issue/BSW-118/swirlfileviewer-shows-wrong-page-number)
To solve the problem, I changed the strategy that defines the current page.
Previously, we defined the current page as the first visible page and, when the user scrolled down to the end of the file, we defined the current page as the last one (actually, that was the bug, because we were defining the second to last page and not the last one).
The new strategy defines the current page as the first most visible page, so that when we have two visible pages, the current one is the most visible, which is the standard behaviour in other file viewers, such as Chrome.
The only edge case I've found is when we have small pages (height) and we can have two full pages …

Fix swirl-file-viewer-pdf current page number

---

.changeset/sweet-dolls-jam.md
packages/swirl-components/src/components/swirl-date-input/swirl-date-input.tsx

Date input did not emit `valueChange` event when the value was changed programatically, causing some issues.
Additionally removed the direct `valueChange` emits as the new watcher should handle those whenever a value changes.

Fix date input value update

---

apps/swirl-docs/src/components/Documentation/EndpointDescription/Parameter.tsx
apps/swirl-docs/src/components/Documentation/EndpointDescription/ParameterFactory.tsx
apps/swirl-docs/src/components/Documentation/Expandable.tsx
apps/swirl-docs/src/lib/docs/src/docs.model.ts
apps/swirl-docs/src/scripts/ApiDocumentation/EndpointMapper.ts

Ticket: ACT-632
This is a follow-up to #844. It turned out that the rendering of properties nested in arrays was not fully implemented, causing a number of rendering problems, one of them us not being able to hide fields that are going to be deprecated.
This PR fixes this and alongside a number of other rendering issues with properties nested in arrays.

getflip.dev - Fix display of nested arrays

---

.changeset/chilly-camels-explode.md
packages/swirl-components/src/components.d.ts
packages/swirl-components/src/components/swirl-image-grid/swirl-image-grid.tsx
packages/swirl-components/src/components/swirl-modal/swirl-modal.css
packages/swirl-components/src/components/swirl-modal/swirl-modal.tsx
packages/swirl-components/src/components/swirl-toggle-group/swirl-toggle-group.css
packages/swirl-components/vscode-data.json

The `post-preview` requires specific styles for the secondary content configuration. Added the option to specify the widths and flex properties of both the primary and secondary content, along with removing some paddings/borders.
Fixed the issue that the `swirl-image-grid` had, as it would not remove overlays (the +2 blurred text) as items were dynamically added/removed.
Added a box shadow to `the swirl-toggle-group`

Adjust the swirl-modal for post preview

---

.changeset/twelve-lobsters-happen.md
packages/swirl-components/src/components.d.ts
packages/swirl-components/src/components/swirl-modal/swirl-modal.tsx
packages/swirl-components/src/components/swirl-switch/swirl-switch.tsx
packages/swirl-components/vscode-data.json
packages/swirl-tokens/dart/lib/styles.dark.dart
packages/swirl-tokens/dart/lib/styles.light.dart

Added the option to modify the `min-height` and the `gap` of modal content containers.
Added the option to define the `aria-label` for `swirl-switch`.

Additional `swirl-modal` options & `aria-label` in `swirl-switch`

---

.changeset/fluffy-donuts-switch.md
packages/swirl-components/src/components.d.ts
packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout.tsx
packages/swirl-components/vscode-data.json

- [Ticket](https://linear.app/flip/issue/ENG-677/flip-web-disable-mobile-sliding-transitions-for-pages-inside-flutter)
- [Storybook](https://icy-water-049ec4003-892.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlapplayout--docs)

Allow to change the initial mobile view of swirl-app-layout

---

.changeset/poor-spies-fetch.md
packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.tsx

- [Ticket](https://linear.app/flip/issue/ENG-511/check-intersecting-loading-swirl-image-grid-inside-chat)
This solution is based on two ideas:
1. As clients (Angular in our case) render the DOM, these images might at some point be intersecting with the viewport, while it's not visible to the user. Instead of checking all of the intersection entries, we should only check the last one, as it's the "final" state that the user sees.
2. Sometimes browsers won't be able to bundle these intersection entries together, e.g. when you manually reload. This is why I also introduced a debounce so that we again only handle the last state.
Additionally sorted the entries as recommended by MDN

ENG-511 Image intersection issues

---

.changeset/proud-socks-behave.md
packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.spec.tsx
packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.tsx

- [Ticket](https://linear.app/flip/issue/ENG-659/scheduling-posts-starts-on-a-monday)
- [Storybook](https://icy-water-049ec4003-896.westeurope.3.azurestaticapps.net/?path=/docs/components-swirldatepicker--docs)

Determine first day of week for date picker via locale

---

.changeset/seven-taxis-refuse.md
packages/swirl-components/src/components.d.ts
packages/swirl-components/src/components/swirl-carousel/swirl-carousel.css
packages/swirl-components/src/components/swirl-carousel/swirl-carousel.spec.tsx
packages/swirl-components/src/components/swirl-carousel/swirl-carousel.tsx
packages/swirl-components/vscode-data.json

Add optional gradient to SwirlCarousel

---

.changeset/eleven-pigs-look.md
packages/swirl-components/src/components.d.ts
packages/swirl-components/src/components/swirl-resource-list/swirl-resource-list.tsx

Only activate items of swirl-resource-list via Enter when having a controlling element.

Tweak resource list keyboard controls

---

.changeset/shy-ducks-heal.md
packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout-base.css
packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout.stories.ts

When the `swirl-app-layout` had no navigation, the sidebar was only opened after the `setTimeout` on the `showSidebar()` finished, making it fully visible after 600ms instead of the supposed 300ms.
This was never a problem in our current usages of the `swirl-app-layout` because we either have navigation, or we call `changeMobileView()` when we want to open a sidebar.
I had 3 ways to solving the problem:
1. Calling `changeMobileView()` instead of `showSidebar` when I want to open a sidebar.
-> Keep buying the problem.
2. Changing the logic that sets the `app-layout--sidebar-active` css class, and also consider the `sidebarOpening` variable;
-> More centralized, but would distort the meaning of the `active` class.
3. Extend the necessary selectors to also consider the …

Fix slow app layout sidebar

---

.changeset/sour-oranges-hide.md
packages/swirl-components/src/components/swirl-action-list-item/swirl-action-list-item.tsx
packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout.tsx
packages/swirl-components/src/components/swirl-banner/swirl-banner.tsx
packages/swirl-components/src/components/swirl-button/swirl-button.tsx
packages/swirl-components/src/components/swirl-chip/swirl-chip.tsx
packages/swirl-components/src/components/swirl-date-input/swirl-date-input.tsx
packages/swirl-components/src/components/swirl-inline-error/swirl-inline-error.tsx
packages/swirl-components/src/components/swirl-inline-status/swirl-inline-status.tsx
packages/swirl-components/src/components/swirl-menu/swirl-menu.tsx
packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.tsx
packages/swirl-components/src/components/swirl-resource-list-file-item/swirl-resource-list-file-item.tsx
packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.tsx
packages/swirl-components/src/components/swirl-search/swirl-search.tsx
packages/swirl-components/src/components/swirl-text-input/swirl-text-input.tsx
packages/swirl-components/src/components/swirl-time-input/swirl-time-input.tsx
packages/swirl-components/src/components/swirl-toast/swirl-toast.tsx

The `onchange` callback would not be removed with `removeEventListener`. This change should now make sure the listeners are properly removed.

Fix media query listeners

---

.changeset/itchy-buttons-ring.md
packages/swirl-components/src/components/swirl-app-icon/swirl-app-icon.tsx
packages/swirl-components/src/components/swirl-avatar/swirl-avatar.tsx
packages/swirl-components/src/components/swirl-file-viewer/viewers/swirl-file-viewer-image/swirl-file-viewer-image.tsx
packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.tsx

- [Ticket](https://linear.app/flip/issue/ENG-1151/fix-swirl-onloadonerror-listeners)

Replace onLoad/onError img attributes with addEventListener subscriptions

---

.changeset/slow-days-whisper.md
packages/swirl-components/src/components/swirl-carousel/swirl-carousel.css

- Made the arrow buttons always visible if carousel overflows; not just on hover
- Removed the vertical offset of arrow buttons
- [Ticket](https://linear.app/flip/issue/ENG-1114/web-implement-new-post-highlights-design)
- [Design](https://www.figma.com/design/93zCjOHLvWLhkE06liixbr/News-Improvements?node-id=326-151407&p=f&ready-for-dev=1&m=dev)
- [Storybook](https://icy-water-049ec4003-974.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlcarousel--docs)

Minor style adjustments for SwirlCarousel

---

.changeset/nine-peaches-sneeze.md
packages/swirl-components/src/components.d.ts
packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.tsx
packages/swirl-components/vscode-data.json

The label in `swirl-resource-list-item` has some `min-height` set. This gives us the option to unset it.

ENG-788 Set resource-list-item label min-height

---

.changeset/twelve-ants-rush.md
package.json
packages/swirl-components/src/components/swirl-carousel/swirl-carousel.tsx

[Ticket](https://linear.app/flip/issue/ENG-1258/new-highlights-dont-scroll-the-carousel-to-the-left)

Update the SwirlCarousel scroll position when resized

---

.changeset/nasty-rats-remain.md
packages/swirl-components/src/components/swirl-modal/swirl-modal.tsx

Fix SwirlModal body scroll unlock exception

---

.changeset/poor-walls-complain.md
.github/workflows/build-deploy.yml
packages/swirl-components/src/components/swirl-menu/swirl-menu.spec.tsx
packages/swirl-components/src/components/swirl-popover/swirl-popover.css
packages/swirl-components/src/components/swirl-popover/swirl-popover.spec.tsx
packages/swirl-components/src/components/swirl-popover/swirl-popover.tsx

- [Ticket](https://linear.app/flip/issue/ENG-1691/save-button-moves-out-of-view-port-when-more-and-more-images-are)
The popover always had a `display: inline-flex` which could mess up the layout flow of pages, even when the popover was closed. This change applies `display: none` to closed popovers.

Hide closed SwirlPopovers entirely

---

.github/workflows/build-deploy.yml
.github/workflows/lint-test.yml
.github/workflows/publish.yml
.github/workflows/sonarqube.yml
package.json
packages/swirl-components/src/components/swirl-action-list-item/swirl-action-list-item.stories.ts

One of the post-install scripts (of a dependency) is timing out in Github actions, so I …
- added `yarn install --ignore-scripts` to the workflows
- moved the `patch-package` script from the `post-install` to the `prebuild` step
In my manual tests omitting the post-install scripts (other than `patch-package`) of the dependencies seemed fine. For the `publish` workflow we need to merge and check on main.
A nice side-effect: This speeds up the workflows by a lot.

Fix yarn install in Github actions

---

.changeset/honest-guests-dance.md
packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.css

- [Ticket](https://linear.app/flip/issue/EMPWEB-67/section-collapse-is-not-working-menu-items-admin-console)
The collapse of swirl-table-row-group did not work due to the change here https://github.com/getflip/swirl/pull/770/files.
Since it sets the height to 0 it needs an `overflow: hidden`. Height 0 will not work with `display: contents`, and a simple `overflow: hidden` would break our sticky column logic. Only thing that worked is `visible` for the x-axis, and `clip` for the y-axis

Fix collapse behavior of swirl-table-row-group

---

.changeset/itchy-months-sin.md
packages/swirl-components/src/components/swirl-file-viewer/viewers/swirl-file-viewer-pdf/swirl-file-viewer-pdf.tsx

- [Ticket](https://linear.app/flip/issue/ENG-1949/kb-pdf-preview-print-pdf-breaks-the-website)

Fix PDF printing crashes

---

.changeset/fresh-moons-explain.md
packages/swirl-components/src/components.d.ts
packages/swirl-components/src/components/swirl-resource-list-file-item/swirl-resource-list-file-item.spec.tsx
packages/swirl-components/src/components/swirl-resource-list-file-item/swirl-resource-list-file-item.tsx
packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.spec.tsx
packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.tsx
packages/swirl-components/src/components/swirl-resource-list-section/swirl-resource-list-section.spec.tsx
packages/swirl-components/src/components/swirl-resource-list-section/swirl-resource-list-section.tsx
packages/swirl-components/src/components/swirl-resource-list/swirl-resource-list.spec.tsx
packages/swirl-components/src/components/swirl-resource-list/swirl-resource-list.tsx
packages/swirl-components/src/components/swirl-stack/swirl-stack.tsx
packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.spec.tsx
packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.tsx
packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.spec.tsx
packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.tsx
packages/swirl-components/vscode-data.json

**Resource list:**
- new prop `semantics: 'grid' | 'list'` on swirl-resource-list
- list semantics disable custom keyboard controls and set role to "list"
- items adjust their roles automatically (`row` and `gridcell` to `listitem`)
- swirl-resource-list-section  poses as a `listitem` with a nested child list when list semantics are used
**Tree view:**
- new prop `semantics: 'tree' | 'list'` on swirl-tree-view
- list semantics disable custom keyboard controls and set role to "list"
- list semantics disable expanding/collapsing items
- items adjust their roles automatically (`treeitem` to `listitem`)

Add alternative "list" semantics to SwirlResourceList and SwirlTreeView

---

.changeset/two-spoons-hope.md
packages/swirl-components/src/components.d.ts
packages/swirl-components/src/components/swirl-modal/swirl-modal.css
packages/swirl-components/src/components/swirl-modal/swirl-modal.tsx
packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.tsx
packages/swirl-components/vscode-data.json

- [Ticket](https://linear.app/flip/issue/EMPWEB-39/show-event-participants-grouped-by-rsvp-response-on-web)

EMPWEB-39 Add option to allow resource-list-item content, hide header border for scrolled modal

---

.changeset/loud-balloons-call.md
packages/swirl-components/src/components/swirl-shell-layout/swirl-shell-layout.css

Fix shell-layout navigation spacing for tiled variant

---

.changeset/gentle-coins-appear.md
.changeset/spotty-trainers-sniff.md
packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.css

When the browser gives focus back to the item, there was a gray background color visible, we can avoid this by using the :focus-visible to control when the focus is visible

Use :focus-visible instead of :focus for swirl-resource-list-item styles
