- .github/workflows/figma-to-style-dictionary.yml
- packages/swirl-tokens/package.json
- packages/swirl-tokens/tsconfig.json
- yarn.lock
Github Action to generate and auto-commit Style Dictionary JSON after token push from Figma.
> APP-11243 figma to style dictionary workflow

- .changeset/neat-bees-knock.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-thumbnail/flip-thumbnail.css
- packages/swirl-components/src/components/flip-thumbnail/flip-thumbnail.mdx
- packages/swirl-components/src/components/flip-thumbnail/flip-thumbnail.spec.tsx
- packages/swirl-components/src/components/flip-thumbnail/flip-thumbnail.stories.ts
- packages/swirl-components/src/components/flip-thumbnail/flip-thumbnail.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-11338/Web-Component-Thumbnail)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Flip-Components?node-id=205%3A4336)
- [Storybook](https://gentle-water-054ae5203-42.westeurope.1.azurestaticapps.net/?path=/docs/components-flipthumbnail--flip-thumbnail)
> APP-11338 web component thumbnail

- .changeset/weak-bees-eat.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-tag/flip-tag.css
- packages/swirl-components/src/components/flip-tag/flip-tag.mdx
- packages/swirl-components/src/components/flip-tag/flip-tag.spec.tsx
- packages/swirl-components/src/components/flip-tag/flip-tag.stories.ts
- packages/swirl-components/src/components/flip-tag/flip-tag.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-11339/Web-Component-Tags)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Flip-Components?node-id=152%3A4591)
- [Storybook](https://gentle-water-054ae5203-41.westeurope.1.azurestaticapps.net/?path=/docs/components-fliptag--flip-tag)
> APP-11339 web component tag

- .changeset/cool-papayas-rule.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-tab/flip-tab.css
- packages/swirl-components/src/components/flip-tab/flip-tab.mdx
- packages/swirl-components/src/components/flip-tab/flip-tab.spec.tsx
- packages/swirl-components/src/components/flip-tab/flip-tab.stories.ts
- packages/swirl-components/src/components/flip-tab/flip-tab.tsx
- packages/swirl-components/src/components/flip-tabs/flip-tabs.css
- packages/swirl-components/src/components/flip-tabs/flip-tabs.mdx
- packages/swirl-components/src/components/flip-tabs/flip-tabs.spec.tsx
- packages/swirl-components/src/components/flip-tabs/flip-tabs.stories.ts
- packages/swirl-components/src/components/flip-tabs/flip-tabs.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-11542/Web-Component-Tabs)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Flip-Components?node-id=34%3A6419)
- Storybook: [FlipTab](https://gentle-water-054ae5203-49.westeurope.1.azurestaticapps.net/?path=/docs/components-fliptab--flip-tab) + [FlipTabs](https://gentle-water-054ae5203-49.westeurope.1.azurestaticapps.net/?path=/docs/components-fliptabs--flip-tabs)
> APP-11542 web component tabs

- .changeset/sour-eels-sort.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-button-group/flip-button-group.css
- packages/swirl-components/src/components/flip-button-group/flip-button-group.mdx
- packages/swirl-components/src/components/flip-button-group/flip-button-group.stories.ts
- packages/swirl-components/src/components/flip-button-group/flip-button-group.tsx
- packages/swirl-components/src/components/flip-button/flip-button.css
- packages/swirl-components/src/styles/global.css
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-12025/Web-Component-Add-Segmented-Button-Group-Variant)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=2%3A16)
- [Storybook](https://gentle-water-054ae5203-75.westeurope.1.azurestaticapps.net/?path=/docs/components-flipbuttongroup--flip-button-group)
> APP-12025 web component segmented button group

- .changeset/giant-apes-raise.md
- .changeset/hot-shirts-accept.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-avatar/flip-avatar.css
- packages/swirl-components/src/components/flip-avatar/flip-avatar.spec.tsx
- packages/swirl-components/src/components/flip-avatar/flip-avatar.tsx
- packages/swirl-components/src/components/flip-badge/flip-badge.css
- packages/swirl-components/src/components/flip-badge/flip-badge.tsx
- packages/swirl-components/vscode-data.json
- packages/swirl-tokens/figma-tokens.json
- packages/swirl-tokens/scripts/utils.ts
- packages/swirl-tokens/tokens/tokens.dark.json
- packages/swirl-tokens/tokens/tokens.light.json
Introduces new breaking changes for our tokens. The decorative tokens were renamed and got different values. This made some adjustments for the FlipAvatar and FlipBadge components necessary.
> Update Figma tokens

- .changeset/nervous-berries-ring.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-box/flip-box.css
- packages/swirl-components/src/components/flip-box/flip-box.mdx
- packages/swirl-components/src/components/flip-box/flip-box.spec.tsx
- packages/swirl-components/src/components/flip-box/flip-box.stories.ts
- packages/swirl-components/src/components/flip-box/flip-box.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-12104/Web-Component-Box)
- [Storybook](https://gentle-water-054ae5203-79.westeurope.1.azurestaticapps.net/?path=/docs/components-flipbox--flip-box)
> APP-12104 web component box

- packages/swirl-tokens/figma-tokens.json
- packages/swirl-tokens/tokens/tokens.dark.json
- packages/swirl-tokens/tokens/tokens.light.json
The "space-20" token was accidentally removed.
> Add missing token

- packages/swirl-tokens/figma-tokens.json
- packages/swirl-tokens/tokens/tokens.dark.json
- packages/swirl-tokens/tokens/tokens.light.json
> Figma tokens

- apps/swirl-docs/src/components/Grid/index.tsx
- apps/swirl-docs/src/lib/hooks/useDynamicRefs.ts
- apps/swirl-docs/src/pages/icons/components/IconGrid.tsx
implemented custom dynamic refs hook, basic aria component for grid, refactored IconGrid to use Grid logic
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-11796)
> APP-11796: a11y grid

- .changeset/wet-scissors-hang.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-card/flip-card.css
- packages/swirl-components/src/components/flip-card/flip-card.mdx
- packages/swirl-components/src/components/flip-card/flip-card.spec.tsx
- packages/swirl-components/src/components/flip-card/flip-card.stories.ts
- packages/swirl-components/src/components/flip-card/flip-card.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-12240/Web-Component-Card)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=2%3A17)
- [Storybook](https://gentle-water-054ae5203-87.westeurope.1.azurestaticapps.net/?path=/docs/components-flipcard--flip-card)
> APP-12240 web component card

- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-file-viewer/flip-file-viewer.stories.ts
- packages/swirl-components/src/components/flip-file-viewer/viewers/flip-file-viewer-image/flip-file-viewer-image.tsx
- packages/swirl-components/src/components/flip-lightbox/flip-lightbox.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-12271/Enable-image-zoom-in-file-viewer-and-lightbox)
- [Storybook](https://gentle-water-054ae5203-96.westeurope.1.azurestaticapps.net/?path=/docs/components-fliplightbox--flip-lightbox)
**To avoid conflicts with other clicks in the lightbox, I put the zoom for desktop on the double click and mouse wheel event.**
> APP-12271 file viewer image zoom

- .changeset/proud-birds-dance.md
> chore: :ambulance: Added changeset for package.json change

- apps/swirl-docs/src/components/ComponentPreview/VariantPreview.tsx
- apps/swirl-docs/src/components/Layout/DocLinksNav.tsx
- apps/swirl-docs/src/components/Layout/DocumentationLayout.tsx
- apps/swirl-docs/src/components/Tokens/TokensList.tsx
- apps/swirl-docs/src/lib/docs/src/docs.model.ts
- apps/swirl-docs/src/lib/docs/src/links.ts
- apps/swirl-docs/src/lib/hooks/useScrollObserver.ts
- apps/swirl-docs/src/lib/hooks/useToC.ts
- apps/swirl-docs/src/pages/components/[componentDoc].tsx
- apps/swirl-docs/src/pages/icons/[iconDoc].tsx
- apps/swirl-docs/src/pages/tokens/[tokenDoc].tsx
- [APP-12197](https://flipapp.myjetbrains.com/youtrack/issue/APP-12197)
> App 12197 swirl docs scroll observer big sites

- .changeset/giant-bugs-marry.md
- packages/swirl-components/src/components/flip-action-list-item/flip-action-list-item.css
- packages/swirl-components/src/components/flip-avatar/flip-avatar.css
- packages/swirl-components/src/components/flip-banner/flip-banner.css
- packages/swirl-components/src/components/flip-button/flip-button.css
- packages/swirl-components/src/components/flip-card/flip-card.css
- packages/swirl-components/src/components/flip-date-input/flip-date-input.css
- packages/swirl-components/src/components/flip-option-list-item/flip-option-list-item.css
- packages/swirl-components/src/components/flip-pagination/flip-pagination.css
- packages/swirl-components/src/components/flip-pdf-reader/flip-pdf-reader.css
- packages/swirl-components/src/components/flip-resource-list-file-item/flip-resource-list-file-item.css
- packages/swirl-components/src/components/flip-resource-list-item/flip-resource-list-item.css
- packages/swirl-components/src/components/flip-search/flip-search.css
- packages/swirl-components/src/components/flip-tabs/flip-tabs.css
- packages/swirl-components/src/components/flip-tag/flip-tag.css
- packages/swirl-components/src/components/flip-text-input/flip-text-input.css
- packages/swirl-components/src/components/flip-tree-navigation-item/flip-tree-navigation-item.css
- packages/swirl-components/src/components/flip-video-thumbnail/flip-video-thumbnail.css
Added :focus-visible selectors to interactive component styles.
- [Storybook](https://gentle-water-054ae5203-108.westeurope.1.azurestaticapps.net/?path=/story/introduction--page)
> Tweak focus styles

- .changeset/serious-bulldogs-type.md
- apps/swirl-docs/src/components/HeaderNavigation/index.tsx
- apps/swirl-docs/tailwind.config.js
- packages/swirl-tokens/dart/lib/styles.dark.dart
- packages/swirl-tokens/dart/lib/styles.light.dart
- packages/swirl-tokens/scripts/build.ts
- packages/swirl-tokens/scripts/utils.ts
- Ticket: [APP-12838](https://flipapp.myjetbrains.com/youtrack/issue/APP-12838)
> APP-12838 export light and dark theme for tailwind tokens

- apps/swirl-docs/public/robots.txt
- apps/swirl-docs/src/lib/docs/src/multipleDocs.ts
- apps/swirl-docs/src/pages/components/[componentDoc].tsx
- apps/swirl-docs/src/pages/sitemap.xml.ts
Ticket: [APP-12906](https://flipapp.myjetbrains.com/youtrack/issue/APP-12906)
> App 12906: Add sitemap.xml and robots.txt

- apps/swirl-docs/src/lib/gtm/index.tsx
- apps/swirl-docs/src/pages/_app.tsx
- apps/swirl-docs/src/pages/_document.tsx
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-12918)
> APP-12918 - GTM Integration

- .changeset/calm-wasps-worry.md
- packages/bridge/README.md
- packages/bridge/package.json
- packages/bridge/src/dialog/dialog.spec.ts
- packages/bridge/src/dialog/dialog.ts
- packages/bridge/src/dialog/dialog.types.ts
- packages/bridge/src/dialog/index.ts
- packages/bridge/src/events/events.ts
- packages/bridge/src/events/events.types.ts
- packages/bridge/src/index.ts
- packages/bridge/src/types.ts
- yarn.lock
- added new methods and events to README
- implemented methods to create, open, close and destroy dialogs
- implement events to listen to dialog action clicks
> APP-12902 add bridge dialog methods and events

- apps/swirl-docs/src/components/ComponentPreview/CodePreview.tsx
- apps/swirl-docs/src/components/ComponentPreview/PropsTable.tsx
- apps/swirl-docs/src/components/Components/ComponentGrid.tsx
- apps/swirl-docs/src/components/Layout/DocLinksNav.tsx
- apps/swirl-docs/src/components/Layout/DocumentationLayout.tsx
- apps/swirl-docs/src/components/Layout/Footer.tsx
- apps/swirl-docs/src/pages/components/index.tsx
- apps/swirl-docs/src/styles/prism-vs-code-dark.css
[Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-13003)
> APP-13003 Component Previews Design improvements

- .changeset/shaggy-fishes-film.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/flip-action-list/flip-action-list.stories.ts
- packages/swirl-components/src/components/flip-separator/flip-separator.css
- packages/swirl-components/src/components/flip-separator/flip-separator.mdx
- packages/swirl-components/src/components/flip-separator/flip-separator.spec.tsx
- packages/swirl-components/src/components/flip-separator/flip-separator.stories.ts
- packages/swirl-components/src/components/flip-separator/flip-separator.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-13021/Swirl-Separator)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=2683%3A17463&t=W5Pa9Djj1Vca5tlW-0)
- [Storybook](https://gentle-water-054ae5203-134.westeurope.1.azurestaticapps.net/?path=/docs/components-flipseparator--flip-separator)
> APP-13021 web component separator

- .changeset/dirty-islands-allow.md
- packages/swirl-components/package.json
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-date-input/swirl-date-input.spec.tsx
- packages/swirl-components/src/components/swirl-date-input/swirl-date-input.tsx
- packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.css
- packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.spec.tsx
- packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.stories.ts
- packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.tsx
- packages/swirl-components/src/index.ts
- packages/swirl-components/stencil.config.ts
- packages/swirl-components/vscode-data.json
- yarn.lock
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-13217/Refactor-More-accessible-datepicker)
- [Storybook](https://gentle-water-054ae5203-144.westeurope.1.azurestaticapps.net/?path=/docs/components-swirldatepicker--swirl-date-picker)
Integrate https://github.com/Sqrrl/wc-datepicker for better keyboard and screen reader support.
> APP-13217 more accessible datepicker

- .changeset/brave-ladybugs-occur.md
- .changeset/tender-rice-mate.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-skeleton-box/swirl-skeleton-box.css
- packages/swirl-components/src/components/swirl-skeleton-box/swirl-skeleton-box.mdx
- packages/swirl-components/src/components/swirl-skeleton-box/swirl-skeleton-box.spec.tsx
- packages/swirl-components/src/components/swirl-skeleton-box/swirl-skeleton-box.stories.ts
- packages/swirl-components/src/components/swirl-skeleton-box/swirl-skeleton-box.tsx
- packages/swirl-components/src/components/swirl-skeleton-text/swirl-skeleton-text.css
- packages/swirl-components/src/components/swirl-skeleton-text/swirl-skeleton-text.mdx
- packages/swirl-components/src/components/swirl-skeleton-text/swirl-skeleton-text.spec.tsx
- packages/swirl-components/src/components/swirl-skeleton-text/swirl-skeleton-text.stories.ts
- packages/swirl-components/src/components/swirl-skeleton-text/swirl-skeleton-text.tsx
- packages/swirl-components/src/styles/disable-desktop-style-tweaks.css
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-13368/Web-Component-Skeleton)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=2929%3A17884&t=Que3BOUIEmzL9qsn-0)
- [SwirlSkeletonText](https://gentle-water-054ae5203-150.westeurope.1.azurestaticapps.net/?path=/docs/components-swirlskeletontext--swirl-skeleton-text) + [SwirlSkeletonBox](https://gentle-water-054ae5203-150.westeurope.1.azurestaticapps.net/?path=/docs/components-swirlskeletonbox--swirl-skeleton-box)
> APP-13368 web component skeleton

- packages/swirl-components/.eslintrc.js
- packages/swirl-components/components.d.ts
- packages/swirl-components/package.json
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-date-input/swirl-date-input.tsx
- packages/swirl-components/stencil.config.ts
- yarn.lock
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-13409/Upgrade-to-Stencil-3)
- [Storybook](https://gentle-water-054ae5203-152.westeurope.1.azurestaticapps.net/)
> App-13409 migrate to Stencil 3

- .changeset/olive-hairs-double.md
- .changeset/ten-balloons-nail.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-action-list-item/swirl-action-list-item.tsx
- packages/swirl-components/src/components/swirl-action-list/swirl-action-list.css
- packages/swirl-components/src/components/swirl-action-list/swirl-action-list.spec.tsx
- packages/swirl-components/src/components/swirl-action-list/swirl-action-list.tsx
- packages/swirl-components/src/components/swirl-file-viewer/swirl-file-viewer.tsx
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.css
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.spec.tsx
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.stories.ts
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.tsx
- packages/swirl-components/src/components/swirl-pdf-reader/swirl-pdf-reader.css
- packages/swirl-components/src/components/swirl-pdf-reader/swirl-pdf-reader.spec.tsx
- packages/swirl-components/src/components/swirl-pdf-reader/swirl-pdf-reader.stories.ts
- packages/swirl-components/src/components/swirl-pdf-reader/swirl-pdf-reader.tsx
- packages/swirl-components/src/components/swirl-popover/swirl-popover.stories.ts
- packages/swirl-components/src/components/swirl-popover/swirl-popover.tsx
- packages/swirl-components/src/components/swirl-separator/swirl-separator.css
- packages/swirl-components/src/components/swirl-spinner/swirl-spinner.css
- packages/swirl-components/src/components/swirl-spinner/swirl-spinner.tsx
- packages/swirl-components/src/utils.ts
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-13465/Web-Component-Add-custom-menus-to-SwirlLightbox-SwirlPdfReader)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=495%3A7144&t=BbFRWGyGHQAsy969-0)
- Storybook: [SwirlLightbox](https://gentle-water-054ae5203-154.westeurope.1.azurestaticapps.net/?path=/docs/components-swirllightbox--swirl-lightbox) + [SwirlPdfReader](https://gentle-water-054ae5203-154.westeurope.1.azurestaticapps.net/?path=/docs/components-swirlpdfreader--swirl-pdf-reader)
> APP-13465 custom lightbox + pdf reader menus

- apps/swirl-docs/next.config.mjs
- apps/swirl-docs/package.json
- apps/swirl-docs/src/pages/_app.tsx
- apps/swirl-docs/src/pages/api/login.ts
- apps/swirl-docs/src/pages/api/passwordCheck.ts
[Ticket](https://flipapp.myjetbrains.com/issue/APP-13734) Add password protection to nextjs app
> password protection added

- .changeset/chatty-frogs-compete.md
- .changeset/clean-owls-heal.md
- .changeset/slow-masks-exist.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.css
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.mdx
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.spec.tsx
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.stories.ts
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.tsx
- packages/swirl-components/src/components/swirl-heading/swirl-heading.css
- packages/swirl-components/src/components/swirl-heading/swirl-heading.tsx
- packages/swirl-components/src/components/swirl-modal/swirl-modal.css
- packages/swirl-components/src/components/swirl-modal/swirl-modal.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-13901/Web-Component-App-Bar)
- [Design](https://www.figma.com/file/IqrF0iX9tsuOUshXb20HsS/Desktop-App?node-id=742%3A182985&t=YgOVrGrWA4Ll6Glc-0)
- [Storybook](https://gentle-water-054ae5203-178.westeurope.1.azurestaticapps.net/?path=/docs/components-swirlappbar--swirl-app-bar)
> APP-13901 web component app bar

- apps/swirl-docs/src/components/ComponentPreview/VariantPreview.tsx
- apps/swirl-docs/src/components/HeaderNavigation/index.tsx
- apps/swirl-docs/src/components/Icons/IconDownload.tsx
- apps/swirl-docs/src/components/Layout/CategoryNav.tsx
- [Ticket](https://flipapp.myjetbrains.com/issue/APP-14051/Fix-Marker.io-Issues)
> marker.io issues

- .changeset/angry-cheetahs-prove.md
- .changeset/giant-cameras-remember.md
- .changeset/silver-bottles-pretend.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-card/swirl-card.css
- packages/swirl-components/src/components/swirl-card/swirl-card.spec.tsx
- packages/swirl-components/src/components/swirl-card/swirl-card.stories.ts
- packages/swirl-components/src/components/swirl-card/swirl-card.tsx
- packages/swirl-components/src/components/swirl-chip/swirl-chip.css
- packages/swirl-components/src/components/swirl-chip/swirl-chip.spec.tsx
- packages/swirl-components/src/components/swirl-chip/swirl-chip.stories.ts
- packages/swirl-components/src/components/swirl-chip/swirl-chip.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-14103/Minor-Swirl-Design-Tweaks)
- Storybook: [Chip](https://gentle-water-054ae5203-197.westeurope.1.azurestaticapps.net/?path=/docs/components-swirlchip--swirl-chip) + [Card](https://gentle-water-054ae5203-197.westeurope.1.azurestaticapps.net/?path=/docs/components-swirlcard--swirl-card)
> APP-14103 component tweaks

- .changeset/dirty-jobs-flow.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-inline-notification/swirl-inline-notification.css
- packages/swirl-components/src/components/swirl-inline-notification/swirl-inline-notification.mdx
- packages/swirl-components/src/components/swirl-inline-notification/swirl-inline-notification.spec.tsx
- packages/swirl-components/src/components/swirl-inline-notification/swirl-inline-notification.stories.ts
- packages/swirl-components/src/components/swirl-inline-notification/swirl-inline-notification.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-14463/Swirl-Component-Inline-Notification)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=3741-28862&t=9COPJq73JA3JmeB8-0)
- [Storybook](https://gentle-water-054ae5203-216.westeurope.1.azurestaticapps.net/?path=/docs/components-swirlinlinenotification--swirl-inline-notification)
> feat(component): add SwirlInlineNotification component

- apps/swirl-docs/src/components/CodePreview/CodePreview.tsx
- apps/swirl-docs/src/components/CodePreview/CodePreviewHighlight.tsx
- apps/swirl-docs/src/components/CodePreview/Select.tsx
- apps/swirl-docs/src/components/Documentation/Parameter.tsx
- apps/swirl-docs/src/components/HeaderNavigation/index.tsx
- apps/swirl-docs/src/components/Layout/DocumentationLayout.tsx
- apps/swirl-docs/src/lib/docs/src/docs.model.ts
- apps/swirl-docs/src/pages/api-docs/[apiSpec].tsx
https://getflipdev-qyjze02xj-getflip.vercel.app/
> APP-15624 api docs request response schemas

- .changeset/chilly-suns-give.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-modal/swirl-modal.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-16002/Adjust-Modal)
- [Storybook](https://icy-water-049ec4003-340.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlmodal--docs)
> APP-16002 modal max-height

- .changeset/lazy-lions-give.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-button/swirl-button.css
- packages/swirl-components/src/components/swirl-thumbnail/swirl-thumbnail.css
- packages/swirl-components/src/components/swirl-thumbnail/swirl-thumbnail.spec.tsx
- packages/swirl-components/src/components/swirl-thumbnail/swirl-thumbnail.stories.ts
- packages/swirl-components/src/components/swirl-thumbnail/swirl-thumbnail.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-16001/Adjust-Thumbnail)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=205%3A4336&mode=dev)
- [Storybook](https://icy-water-049ec4003-342.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlthumbnail--docs)
> APP-16001 extend thumbnail

- .changeset/friendly-maps-learn.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-tab-bar/swirl-tab-bar.css
- packages/swirl-components/src/components/swirl-tab-bar/swirl-tab-bar.stories.ts
- packages/swirl-components/src/components/swirl-tab-bar/swirl-tab-bar.tsx
- packages/swirl-components/src/components/swirl-tab/swirl-tab.stories.ts
- packages/swirl-components/src/components/swirl-tab/swirl-tab.tsx
- packages/swirl-components/src/components/swirl-tabs/swirl-tabs.stories.ts
- packages/swirl-components/src/components/swirl-tabs/swirl-tabs.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-16658/Extend-TabBar-with-leading-icons)
- [Design](https://www.figma.com/file/URwNyWTX2Na0nCZ7HNikAw/Desktop-App-Handover?type=design&node-id=2987-306632&mode=design&t=IOL8FVqQT3AMS3gk-0)
- [TabBar](https://icy-water-049ec4003-354.westeurope.3.azurestaticapps.net/?path=/docs/components-swirltabbar--docs) + [Tabs](https://icy-water-049ec4003-354.westeurope.3.azurestaticapps.net/?path=/docs/components-swirltabs--docs)
> APP-16658 allow icons inside SwirlTabBar tabs

- .changeset/little-apes-lie.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-button/swirl-button.css
- packages/swirl-components/src/components/swirl-button/swirl-button.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-15001/Ghost-and-Outlined-Button-New-State-and-Adjustments)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=2-15&t=zfqrgenv7lc71pKE-11)
- [Storybook](https://icy-water-049ec4003-367.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlbutton--docs)
> APP-15001 button pressed prop

- .changeset/pretty-brooms-notice.md
- packages/swirl-components/src/components/swirl-form-control/swirl-form-control.css
- packages/swirl-components/src/components/swirl-form-control/swirl-form-control.spec.tsx
- packages/swirl-components/src/components/swirl-form-control/swirl-form-control.stories.ts
- packages/swirl-components/src/components/swirl-form-control/swirl-form-control.tsx
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-14657/Text-Input-new-variant)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=545%3A13417&t=gxQVUww2ammI3iLL-1)
- [Storybook](https://icy-water-049ec4003-369.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlformcontrol--docs)
> APP-14657 form control prefix slot

- .changeset/kind-rice-refuse.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-checkbox/swirl-checkbox.css
- packages/swirl-components/src/components/swirl-checkbox/swirl-checkbox.spec.tsx
- packages/swirl-components/src/components/swirl-checkbox/swirl-checkbox.tsx
- packages/swirl-components/src/components/swirl-radio/swirl-radio.css
- packages/swirl-components/src/components/swirl-radio/swirl-radio.spec.tsx
- packages/swirl-components/src/components/swirl-radio/swirl-radio.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-14649/Selectable-Card)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=3886%3A33584&t=EgtyVLESFDDrkrnf-1)
- Storybook: [Checkbox](https://icy-water-049ec4003-371.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlcheckbox--docs) + [Radio](https://icy-water-049ec4003-371.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlradio--docs)
> APP-14649 checkbox/radio card variant

- .changeset/gentle-cars-marry.md
- packages/swirl-components/src/components/swirl-action-list/swirl-action-list.tsx
- packages/swirl-components/src/components/swirl-option-list/swirl-option-list.tsx
- packages/swirl-components/src/components/swirl-resource-list/swirl-resource-list.spec.tsx
- packages/swirl-components/src/components/swirl-resource-list/swirl-resource-list.tsx
- packages/swirl-components/src/components/swirl-select/swirl-select.tsx
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-17344/Refactor-fix-some-Swirl-keyboard-controls)
> APP-17344 fix keyboard controls

- .changeset/four-dolphins-confess.md
- packages/swirl-components/src/components/swirl-autocomplete/swirl-autocomplete.tsx
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-17424/Console-Subgroups-Owner-Entry-Improvement)
- [Storybook](https://icy-water-049ec4003-392.westeurope.3.azurestaticapps.net/?path=/story/components-swirlautocomplete--swirl-autocomplete&args=multiSelect:!true)
> APP-17424 clear autocomplete search after multi selection

- .changeset/brave-cheetahs-enjoy.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-select/swirl-select.css
- packages/swirl-components/src/components/swirl-select/swirl-select.spec.tsx
- packages/swirl-components/src/components/swirl-select/swirl-select.stories.ts
- packages/swirl-components/src/components/swirl-select/swirl-select.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-17460/Console-Replace-user-group-autocompletes-with-select-with-search)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/branch/SUpkwtSeVRcF6upBwmLYt1/Swirl-Components?type=design&node-id=6892%3A59520&mode=design&t=zg3k8toPMJk1VM1R-1)
- [Storybook](https://icy-water-049ec4003-394.westeurope.3.azurestaticapps.net/?path=/story/components-swirlselect--swirl-select)
> APP-17460 select search

- .changeset/smooth-games-tease.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-accordion-item/swirl-accordion-item.css
- packages/swirl-components/src/components/swirl-accordion-item/swirl-accordion-item.mdx
- packages/swirl-components/src/components/swirl-accordion-item/swirl-accordion-item.spec.tsx
- packages/swirl-components/src/components/swirl-accordion-item/swirl-accordion-item.stories.ts
- packages/swirl-components/src/components/swirl-accordion-item/swirl-accordion-item.tsx
- packages/swirl-components/src/components/swirl-accordion/swirl-accordion.css
- packages/swirl-components/src/components/swirl-accordion/swirl-accordion.mdx
- packages/swirl-components/src/components/swirl-accordion/swirl-accordion.spec.tsx
- packages/swirl-components/src/components/swirl-accordion/swirl-accordion.stories.ts
- packages/swirl-components/src/components/swirl-accordion/swirl-accordion.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-17219/New-Accordion)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?type=design&node-id=5714-64436&mode=design)
- Storybook: [Accordion](https://icy-water-049ec4003-401.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlaccordion--docs) + [AccordionItem](https://icy-water-049ec4003-401.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlaccordionitem--docs)
> APP-17219 web component accordion

- .changeset/nice-actors-enjoy.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.css
- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.mdx
- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.spec.tsx
- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.stories.ts
- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.tsx
- packages/swirl-components/stencil.config.ts
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-17617/New-Color-input-with-preview)
- [Design](https://www.figma.com/file/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=3571%3A26021&mode=dev)
- [Storybook](https://icy-water-049ec4003-402.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlcolorinput--docs)
> APP-17617 web component color input

- .changeset/heavy-insects-love.md
- packages/swirl-components/package.json
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.css
- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.spec.tsx
- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.tsx
- packages/swirl-components/stencil.config.ts
- packages/swirl-components/vscode-data.json
- yarn.lock
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-17706/Add-color-picker-to-color-input)
- [Storybook](https://icy-water-049ec4003-407.westeurope.3.azurestaticapps.net/?path=/story/components-swirlcolorinput--swirl-color-input)
> APP-17706 color picker

- .changeset/afraid-stingrays-confess.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-avatar/swirl-avatar.css
- packages/swirl-components/src/components/swirl-avatar/swirl-avatar.spec.tsx
- packages/swirl-components/src/components/swirl-avatar/swirl-avatar.stories.ts
- packages/swirl-components/src/components/swirl-avatar/swirl-avatar.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-17632/Avatar-Badge-as-slot-for-buttons)
- [Design](https://www.figma.com/file/URwNyWTX2Na0nCZ7HNikAw/Desktop-App-Handover?type=design&node-id=3490%3A661176&mode=dev)
- [Storybook](https://icy-water-049ec4003-415.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlavatar--docs)
> APP-17632 avatar tool slot

- .changeset/poor-trainers-wait.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-description-list-item/swirl-description-list-item.css
- packages/swirl-components/src/components/swirl-description-list-item/swirl-description-list-item.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-18152/Implement-tooltip-prop-for-DescriptionListItem-in-Swirl)
- [Storybook](https://icy-water-049ec4003-444.westeurope.3.azurestaticapps.net/?path=/docs/components-swirldescriptionlistitem--docs)
> APP-18152 description list item tooltip

- .changeset/spotty-ducks-drop.md
- packages/swirl-components/package.json
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-popover/swirl-popover.stories.ts
- packages/swirl-components/src/components/swirl-popover/swirl-popover.tsx
- packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.stories.ts
- packages/swirl-components/vscode-data.json
- yarn.lock
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-18235/Fix-ResourceListItem-behavior-with-menu)
- [Storybook](https://icy-water-049ec4003-450.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlpopover--docs)
> APP-18235 returnFocusToTrigger prop for popover

- .changeset/mean-beans-appear.md
- packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.tsx
- packages/swirl-components/src/utils.ts
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-18911/Swirl-Datepicker-Timezone-Bug)
- [Storybook](https://icy-water-049ec4003-459.westeurope.3.azurestaticapps.net/?path=/docs/components-swirldateinput--docs)
> APP-18911 fix timezone issue of swirl date components

- apps/swirl-docs/src/components/Documentation/DocumentationHeader.tsx
- apps/swirl-docs/src/components/Documentation/EndpointDescription.tsx
- apps/swirl-docs/src/components/Layout/DocLinksNav.tsx
- apps/swirl-docs/src/components/Layout/DocumentationLayout.tsx
- apps/swirl-docs/src/components/Tags/index.tsx
- apps/swirl-docs/src/components/swirl-recreations/Headers/index.tsx
- apps/swirl-docs/src/pages/api-docs/docs/[apiDoc].tsx
https://flipapp.myjetbrains.com/youtrack/issue/APP-20124/Implement-API-Docs-Markdown-Styling
> APP-20124 tweak markdown page styles

- .changeset/great-spiders-explain.md
- packages/swirl-components/src/components/swirl-popover-trigger/swirl-popover-trigger.tsx
- packages/swirl-components/src/components/swirl-popover/swirl-popover.tsx
- [Ticket](https://flipapp.myjetbrains.com/youtrack/issue/APP-20227/Bug-Swirl-Popover-Bug-on-stopPropagation-for-MobileNav)
- [Storybook](https://icy-water-049ec4003-483.westeurope.3.azurestaticapps.net/?path=/story/components-swirlpopovertrigger--swirl-popover-trigger)
> APP-20227 keep click event propagation for SwirlPopoverTrigger

- apps/swirl-docs/src/components/Layout/SidebarNavigation.tsx
Close all other open headers when resource path changes
> fix navigation toggle behavior

- apps/swirl-docs/package.json
- apps/swirl-docs/src/components/Tags/index.tsx
- apps/swirl-docs/src/lib/docs/src/ApiDocumentationsFacade.ts
- apps/swirl-docs/src/lib/docs/src/oasBuilder.ts
- package.json
- yarn.lock
- Sort endpoints by path + method
- Show full method name
> Endpoint sorting in navigation, method naming

- .changeset/blue-squids-suffer.md
- package.json
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.css
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.spec.tsx
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://flipapp.myjetbrains.com/youtrack/agiles/115-84/current?issue=APP-21504)
-
> 21504 row group header tooltip

- .changeset/neat-hotels-float.md
- packages/swirl-components/src/components/swirl-switch/swirl-switch.tsx
- [Ticket](https://flipapp.myjetbrains.com/youtrack/agiles/115-84/current?issue=APP-21590)
> remove drag events from swirl-switch

- .changeset/chilly-coins-care.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.css
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.spec.tsx
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.tsx
- packages/swirl-components/src/components/swirl-tooltip/swirl-tooltip.spec.tsx
- packages/swirl-components/src/components/swirl-tooltip/swirl-tooltip.tsx
- packages/swirl-components/vscode-data.json
> APP-21553 Swirl: Fix tooltip positioning

- .changeset/clever-dragons-warn.md
- packages/swirl-components/src/components/swirl-popover-trigger/swirl-popover-trigger.tsx
> Fix error on missing popover trigger element

- .changeset/proud-islands-act.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.css
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.spec.tsx
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.tsx
- packages/swirl-components/src/components/swirl-table/swirl-table.stories.ts
- packages/swirl-components/vscode-data.json
> making row groups collapsable

- .changeset/dry-owls-press.md
- packages/swirl-components/src/components/swirl-time-input/swirl-time-input.spec.tsx
- packages/swirl-components/src/components/swirl-time-input/swirl-time-input.tsx
- [Ticket](#)
- [Design](#)
- Issue: #591 
I tried the `tel` inputmode instead of `numeric` but unfortunely was not better. It did not allow for entering `:` and showed other characters like `*`, `+`, `#` that could be misleading. 
> Open numeric keyboard when inputing time on SwirlTimeInput

- .changeset/early-mirrors-search.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-date-input/swirl-date-input.tsx
- packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.css
- packages/swirl-components/src/components/swirl-date-picker/swirl-date-picker.tsx
- [Ticket](#593)
- [Design](#)
- Issue: #593
> Date picker disable dates

- packages/swirl-components/src/components/swirl-color-input/swirl-color-input.stories.ts
- packages/swirl-components/src/components/swirl-date-input/swirl-date-input.stories.ts
- packages/swirl-components/src/components/swirl-text-input/swirl-text-input.stories.ts
- packages/swirl-components/src/components/swirl-time-input/swirl-time-input.stories.ts
- packages/swirl-components/src/utils.ts
> Fix Storybook form input props

- .changeset/dull-planes-rhyme.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-box/swirl-box.tsx
- packages/swirl-components/vscode-data.json
> implement flex grow and basis for swirl-box

- .changeset/fast-candles-relate.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-date-input/swirl-date-input.spec.tsx
- packages/swirl-components/src/components/swirl-date-input/swirl-date-input.tsx
- packages/swirl-components/src/components/swirl-form-control/swirl-form-control.spec.tsx
- packages/swirl-components/src/components/swirl-form-control/swirl-form-control.tsx
- packages/swirl-components/src/utils.ts
- packages/swirl-components/vscode-data.json
> Add option to open the datepicker at focus in swirl-date-input

- .changeset/fuzzy-geckos-exercise.md
- packages/swirl-components/src/components/swirl-modal/swirl-modal.css
On mobile devices like iOS/Safari,  the lower content of the modal it's hidden by the address bar.
After the fix, the UI should look like this and adapt if the user decides to hide the address bar.
Android Before: 
Android After:
iOS Before:
iOS After:
- [Ticket](#)
- [Design](#)
> fix(components): fix modal too talk when address bar is shown

- .changeset/stupid-icons-applaud.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-dialog/swirl-dialog.tsx
As requested by a partner, the SwirlDialog should have the same api as SwirlModal so that code can be executed when the dialog opens and closes.  
- [Ticket](#)
- [Design](#)
> Add dialogClose and dialogOpen event emitters to SwirlDialog

- .changeset/rich-bats-drum.md
- packages/swirl-components/src/components/swirl-modal/swirl-modal.css
- [Ticket](#)
- [Design](#)
On small devices the modal occupies the full height but not the full width of the screen.
This looks a bit odd. 
Please consider this fix unless the current solution it's by design.
| Before | After |
|--------|--------|
| <img width="769" alt="Screenshot 2024-04-02 at 15 52 37" src="https://github.com/getflip/swirl/assets/2084270/6f628a70-9b50-49b9-a9d6-e857517a9848"> | <img width="768" alt="Screenshot 2024-04-02 at 15 53 11" src="https://github.com/getflip/swirl/assets/2084270/8a704b03-ea3f-4430-8cc3-acf142504204"> |
> Fix SwirlModal max-width on mobile

- packages/swirl-components/src/components/swirl-modal/swirl-modal.css
> fix model height with header tools

- .changeset/late-hounds-care.md
- packages/swirl-components/src/components/swirl-modal/swirl-modal.css
> Set modal content height to 100%

- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-tag/swirl-tag.css
- packages/swirl-components/src/components/swirl-tag/swirl-tag.tsx
- packages/swirl-components/vscode-data.json
> add bordered prop

- .changeset/tall-bobcats-agree.md
- packages/bridge/README.md
- packages/bridge/src/index.ts
- packages/bridge/src/toast/index.ts
- packages/bridge/src/toast/toast.spec.ts
- packages/bridge/src/toast/toast.ts
- packages/bridge/src/toast/toast.types.ts
- packages/bridge/src/types.ts
> feat(bridge): Create showToast method

- .changeset/five-cars-fix.md
- packages/bridge/src/toast/toast.ts
> fix(bridge): Change showToast return type

- .changeset/lucky-mice-know.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-tab-bar/swirl-tab-bar.css
- packages/swirl-components/src/components/swirl-tab-bar/swirl-tab-bar.spec.tsx
- packages/swirl-components/src/components/swirl-tab-bar/swirl-tab-bar.tsx
- packages/swirl-components/src/components/swirl-tab/swirl-tab.css
- packages/swirl-components/src/components/swirl-tab/swirl-tab.spec.tsx
- packages/swirl-components/src/components/swirl-tab/swirl-tab.tsx
- packages/swirl-components/src/components/swirl-tabs/swirl-tabs.spec.tsx
- packages/swirl-components/src/components/swirl-tabs/swirl-tabs.stories.ts
- packages/swirl-components/src/components/swirl-tabs/swirl-tabs.tsx
- packages/swirl-components/vscode-data.json
> Update swirl tabs

- .changeset/long-baboons-decide.md
- packages/swirl-components/src/components/swirl-action-list-item/swirl-action-list-item.css
- packages/swirl-components/src/components/swirl-action-list-item/swirl-action-list-item.tsx
> Adjust suffix prop of menu item to render tag

- .changeset/neat-pears-push.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-tag/swirl-tag.css
- packages/swirl-components/src/components/swirl-tag/swirl-tag.spec.tsx
- packages/swirl-components/src/components/swirl-tag/swirl-tag.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/BSW-34/extend-swirl-tags-component)
- [Design](https://www.figma.com/design/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=152-4591&m=dev)
> Extend swirl-tag

- .changeset/lovely-vans-stare.md
- packages/swirl-components/src/components/swirl-table-cell/swirl-table-cell.css
- packages/swirl-components/src/components/swirl-table-column/swirl-table-column.css
- packages/swirl-components/src/components/swirl-table-row-group/swirl-table-row-group.css
- packages/swirl-components/src/components/swirl-table/swirl-table.css
- packages/swirl-components/src/components/swirl-table/swirl-table.tsx
- [Ticket](#) https://linear.app/flip/issue/ACT-213/make-bulk-action-and-row-actions-a-sticky-column-in-all-console-tables
- [Design](#) https://www.figma.com/design/iRHiAFsHxnzux8gQ9EjlZe/Swirl-Components?node-id=2433-31531&m=dev
- [Storybook](#) https://swirl-storybook.flip-app.dev/?path=/docs/components-swirltable--docs
> Apply sticky property to table columns and cells

- .changeset/mean-beds-share.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-resource-list/swirl-resource-list.spec.tsx
- packages/swirl-components/src/components/swirl-resource-list/swirl-resource-list.tsx
- packages/swirl-components/vscode-data.json
- [BSW-138: Add small gap between list items](https://linear.app/flip/issue/BSW-138/add-small-gap-between-list-items)
> Add spacing to swirl resource list

- .changeset/forty-tips-add.md
- packages/swirl-components/.storybook/preview-head.html
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.css
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.mdx
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.spec.tsx
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.stories.ts
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.tsx
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.css
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.mdx
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.spec.tsx
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.stories.ts
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/ENG-196/new-tree-navigation-item-in-swirl)
- [Design](https://www.figma.com/design/t6ISOeXcBoEErcolnLivai/Pages?node-id=773-176934&node-type=SECTION&m=dev)
- [Storybook](https://icy-water-049ec4003-789.westeurope.3.azurestaticapps.net/?path=/docs/components-swirltreeview--docs)
> Add SwirlTreeView + SwirlTreeViewItem components

- .changeset/clever-olives-grow.md
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.spec.tsx
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.tsx
- [BSW-150](https://linear.app/flip/issue/BSW-150/i-can-move-the-live-stream-video-player)
> Remove drag behavior when the swirl-lightbox has only one item

- .changeset/three-mails-fry.md
- packages/swirl-components/src/components/swirl-select/swirl-select.tsx
- [BSW-173](https://linear.app/flip/issue/BSW-173/fix-valuechange-event-in-swirl-select)
According to the report, the `valueChange` event was emitted twice, when listened from the `swirl-select`. This was due to the `valueChange` event being bubbled from the `swirl-option-list`.
The strategy followed was to stop the propagation in the `swirl-select`, as it's done in `swirl-autocomplete`.
> Prevent valueChange event propagation in swirl-select

- .changeset/late-papayas-promise.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout-base.css
- packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout-transitions.css
- packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout.spec.tsx
- packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout.stories.ts
- packages/swirl-components/src/components/swirl-app-layout/swirl-app-layout.tsx
- packages/swirl-components/src/components/swirl-shell-layout/swirl-shell-layout.stories.ts
- packages/swirl-components/src/index.ts
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/ENG-203/make-navigation-column-in-news-collapsable)
> Make SwirlAppLayout navigation collapsible

- .changeset/popular-dolls-mate.md
- packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.css
Even though the items were displayed in `block`, the browser would calculate the width of them if they were displayed `inline`, making the width of the items as large as the number of items there were.
> fix(components): Fix swirl-option-list-item applied width

- .changeset/cyan-forks-wash.md
- packages/swirl-components/src/components/swirl-date-input/swirl-date-input.tsx
- [Ticket](https://linear.app/flip/issue/ENG-375/event-creation-date-picker-shows-incorrect-month-view) 
- [Design](#)
- [Storybook](#)]
> Pass the start date to the datepicker inside dateinput

- .changeset/forty-bats-juggle.md
- packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.css
- packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.spec.tsx
- packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.stories.ts
- packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.tsx
- [Ticket](https://linear.app/flip/issue/ENG-420/implement-post-on-behalf-management-within-admin-console)
- [Design](https://www.figma.com/design/fISX53jBFnBqfY3jp9W1PO/Post-on-behalf-of?node-id=266-38800&node-type=instance&m=dev)
- [Storybook](https://icy-water-049ec4003-835.westeurope.3.azurestaticapps.net/?path=/docs/components-swirloptionlistitem--docs)
> add "avatar" slot to SwirlOptionListItem

- .changeset/three-dryers-serve.md
- packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.stories.ts
- packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.tsx
> improve loading and gif behaviour

- .changeset/new-forks-flash.md
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.css
If the app bar has a large heading, it doesn't allow it to be truncated, but rather scrolls the container, which hides the center and right controls if they are defined.
> Fix app bar heading

- .changeset/sixty-bugs-wink.md
- packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.tsx
- packages/swirl-components/src/components/swirl-shell-layout/swirl-shell-layout.stories.ts
- packages/swirl-components/src/components/swirl-shell-navigation-item/swirl-shell-navigation-item.css
- [Ticket](https://linear.app/flip/issue/ENG-435/improvement-on-menu-tile)
- [Storybook](https://icy-water-049ec4003-850.westeurope.3.azurestaticapps.net/)
> Hide gradient for small shell nav items

- .changeset/two-suns-joke.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-tag/swirl-tag.css
- packages/swirl-components/src/components/swirl-tag/swirl-tag.spec.tsx
- packages/swirl-components/src/components/swirl-tag/swirl-tag.tsx
- packages/swirl-components/vscode-data.json
> Add icon position to swirl tag

- .changeset/large-mugs-attend.md
- packages/swirl-components/src/components/swirl-tag/swirl-tag.tsx
> Force icon props on icon change in swirl-tag

- .changeset/stupid-moose-behave.md
- packages/swirl-components/src/components/swirl-separator/swirl-separator.css
- packages/swirl-components/src/components/swirl-separator/swirl-separator.tsx
- packages/swirl-components/vscode-data.json
> Add highlight color to swirl-separator

- .changeset/tame-bulldogs-give.md
- packages/swirl-components/src/components/swirl-select/swirl-select.css
- [Ticket](#) https://linear.app/flip/issue/ACT-689/fix-layout-of-swirl-select-component-with-multi-select
- [Design](#)
> Act 689 fix layout of swirl select component with multi select

- .changeset/stale-tigers-visit.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-card/swirl-card.tsx
- [Ticket](https://linear.app/flip/issue/ENG-687/improve-chat-group-mentions-separator)
> Emit a componentLoad event from swirl-card

- .changeset/honest-ants-beg.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-button-group/swirl-button-group.spec.tsx
- packages/swirl-components/src/components/swirl-button-group/swirl-button-group.tsx
- packages/swirl-components/vscode-data.json
> Allow to specify SwirlButtonGroup spacing

- .changeset/sweet-boats-rest.md
- packages/swirl-components/src/components/swirl-button/swirl-button.css
> Fix swirl button style for outline primary

- .changeset/green-dancers-sneeze.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-popover/swirl-popover.spec.tsx
- packages/swirl-components/src/components/swirl-popover/swirl-popover.tsx
- [Storybook](https://icy-water-049ec4003-921.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlpopover--docs)
> Popover isOpen() method

- .changeset/flat-elephants-look.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-action-list-item/swirl-action-list-item.css
- [Ticket](https://linear.app/flip/issue/ENG-826/update-color-on-swril-menu-component)
> Adjust swirl-action-list-item suffix icon color

- .changeset/dull-coins-buy.md
- packages/swirl-components/src/components/swirl-tab-bar/swirl-tab-bar.tsx
- [Ticket](https://linear.app/flip/issue/ENG-877/update-tabs-on-web)
> Eng 877 scroll focused tab into view

- packages/swirl-components/src/components/swirl-chip/swirl-chip.tsx
- packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.tsx
- packages/swirl-components/src/components/swirl-select/swirl-select.tsx
- packages/swirl-components/src/components/swirl-tag/swirl-tag.tsx
> Improvements on SwirlSelect

- .changeset/shy-walls-compare.md
- packages/error-code-generator/package.json
- packages/error-code-generator/src/types/index.ts
- yarn.lock
> 920 major upgrade for jsonpath plus

- .changeset/empty-trainers-double.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-inline-notification/swirl-inline-notification.tsx
- packages/swirl-components/vscode-data.json
> add hide heading prop

- .changeset/dirty-cobras-work.md
- packages/swirl-components/package.json
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.css
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.spec.tsx
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.tsx
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.config.ts
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.css
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.spec.tsx
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.stories.ts
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.tsx
- packages/swirl-components/src/index.ts
- packages/swirl-components/vscode-data.json
- yarn.lock
- [Ticket](https://linear.app/flip/issue/ENG-872/spike-pages-drag-and-drop)
- [Storybook](https://icy-water-049ec4003-936.westeurope.3.azurestaticapps.net/?path=/story/components-swirltreeview--swirl-tree-view)
> Drag & Drop support for swirl-tree-view

- .changeset/funny-cheetahs-kick.md
- packages/swirl-components/src/components/swirl-dialog/swirl-dialog.css
- packages/swirl-components/src/components/swirl-dialog/swirl-dialog.spec.tsx
- packages/swirl-components/src/components/swirl-dialog/swirl-dialog.tsx
- packages/swirl-components/src/components/swirl-switch/swirl-switch.css
> Support custom controls in Swirl Dialog

- README.md
- packages/swirl-components/README.md
- packages/swirl-tokens/README.md
https://linear.app/flip/issue/ENG-1080/update-swirl-readme
> Update README files

- .changeset/wise-starfishes-hunt.md
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.stories.ts
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.tsx
In the case that `fileName` was specified on `SwirlFileViewer` it's not respected on `SwirlLightbox` popover.
- [Ticket](#)
- [Design](#)
> Swirl align filename between lightbox and fileviewer

- .changeset/sixty-oranges-matter.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-avatar/swirl-avatar.tsx
- packages/swirl-components/src/components/swirl-table-row/swirl-table-row.css
- packages/swirl-components/src/components/swirl-table/swirl-table.css
- packages/swirl-components/src/components/swirl-table/swirl-table.spec.tsx
- packages/swirl-components/src/components/swirl-table/swirl-table.stories.ts
- packages/swirl-components/src/components/swirl-table/swirl-table.tsx
- packages/swirl-components/src/index.ts
- packages/swirl-components/src/styles/global.css
- packages/swirl-components/vscode-data.json
https://icy-water-049ec4003-965.westeurope.3.azurestaticapps.net/?path=/story/components-swirltable--swirl-table
> Drag & drop for swirl-table

- .changeset/thirty-pillows-battle.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-popover/swirl-popover.css
- packages/swirl-components/src/components/swirl-resource-list/swirl-resource-list.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/ENG-1001/inherit-color-in-mention-popover-web)
- [Storybook](https://icy-water-049ec4003-978.westeurope.3.azurestaticapps.net/?path=/docs/components-swirlresourcelist--docs)
> Add padding props to swirl-resource-list

- .changeset/cold-fans-drum.md
- packages/swirl-components/src/components/swirl-carousel/swirl-carousel.spec.tsx
- packages/swirl-components/src/components/swirl-carousel/swirl-carousel.tsx
> fix carousel slide scrolling parent container

- packages/swirl-components/src/components/swirl-image-grid/swirl-image-grid.tsx
> use aspect ratio when given

- .changeset/five-students-travel.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-file-uploader/swirl-file-uploader.tsx
- packages/swirl-components/vscode-data.json
> add allow-html and hide-label props to file uploader

- .changeset/famous-oranges-roll.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-stack/swirl-stack.spec.tsx
- packages/swirl-components/src/components/swirl-stack/swirl-stack.tsx
- packages/swirl-components/vscode-data.json
> Add columnSpacing and rowSpacing props to swirl-stack

- .changeset/good-feet-sparkle.md
- packages/swirl-components/src/components/swirl-tree-view-item/swirl-tree-view-item.css
- packages/swirl-components/src/components/swirl-tree-view/swirl-tree-view.stories.ts
https://linear.app/flip/issue/ENG-1265/alignment-bug-with-menu-items-in-the-knowledge-base
> Fix SwirlTreeViewItem drag handle sizing

- .changeset/warm-camels-own.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-file-viewer/swirl-file-viewer.spec.tsx
- packages/swirl-components/src/components/swirl-file-viewer/swirl-file-viewer.stories.ts
- packages/swirl-components/src/components/swirl-file-viewer/swirl-file-viewer.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/MOB-899/add-download-event-for-file-download-related-swirl-components)
- [Design](#)
> feat: add support for manual file downloads

- .changeset/kind-meals-own.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-modal/swirl-modal.css
- packages/swirl-components/src/components/swirl-modal/swirl-modal.spec.tsx
- packages/swirl-components/src/components/swirl-modal/swirl-modal.stories.ts
- packages/swirl-components/src/components/swirl-modal/swirl-modal.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/AUT-699/swirl-extend-modal-to-have-a-sidebar-to-the-left)
- [Design](#)
> feat: add sidebar to SwirlModal

- .changeset/stupid-ladybugs-chew.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-file-viewer/swirl-file-viewer.tsx
- packages/swirl-components/src/components/swirl-file-viewer/viewers/swirl-file-viewer-fallback/swirl-file-viewer-fallback.tsx
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.stories.ts
- packages/swirl-components/src/components/swirl-pdf-reader/swirl-pdf-reader.stories.ts
- packages/swirl-components/src/components/swirl-pdf-reader/swirl-pdf-reader.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/MOB-899/add-download-eventg-file-download-related-swirl-components)
- [Design](#)
> feat: support manual file download for swirl-pdf-reader and swirl-file-viewer-fallback

- .changeset/pretty-stingrays-design.md
- packages/swirl-components/src/components/swirl-modal/swirl-modal.css
> Fix content width of swirl modal

- .changeset/old-clocks-sell.md
- packages/bridge/README.md
- packages/bridge/src/download/download.spec.ts
- packages/bridge/src/download/download.ts
- packages/bridge/src/download/download.types.ts
- packages/bridge/src/download/index.ts
- packages/bridge/src/types.ts
- [Ticket](https://linear.app/flip/issue/MOB-225/add-bridge-download-method)
- [Design](#)
> feat: add bridge download method

- .changeset/witty-shrimps-tap.md
- packages/swirl-components/src/components/swirl-select/swirl-select.spec.tsx
- packages/swirl-components/src/components/swirl-select/swirl-select.tsx
[Ticket](https://linear.app/flip/issue/ENG-1246/managing-user-group-input-field-bug)
> Fix valueChange event for swirl-select's external value changes

- .changeset/sour-hats-hang.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-carousel/swirl-carousel.css
- packages/swirl-components/src/components/swirl-carousel/swirl-carousel.spec.tsx
- packages/swirl-components/src/components/swirl-carousel/swirl-carousel.tsx
- packages/swirl-components/vscode-data.json
Now that SwirlCarousel started to be used with fade enabled on top of different background colors, there's the need to allow to customize the fade color.
- [Ticket](#)
- [Design](#)
> Allow different fade colors on SwirlCarousel

- .changeset/chilled-ducks-kick.md
- packages/swirl-components-react/package.json
> Move react + react-dom to peerDeps

- .changeset/metal-bugs-battle.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-button/swirl-button.css
- packages/swirl-components/src/components/swirl-button/swirl-button.tsx
- packages/swirl-components/src/components/swirl-toggle-group/swirl-toggle-group.css
- packages/swirl-components/src/components/swirl-toggle-group/swirl-toggle-group.tsx
- packages/swirl-components/vscode-data.json
> Add elevated prop to swirl-button and swirl-toggle-group

- .changeset/modern-cherries-give.md
- packages/swirl-components/src/components/swirl-button/swirl-button.css
- packages/swirl-components/src/components/swirl-toggle-group/swirl-toggle-group.css
> Use swirl token for elevated shadow in swirl-button and swirl-toggle-group

- .changeset/plenty-poets-count.md
- packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.css
- packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.spec.tsx
- packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.tsx
- packages/swirl-components/src/components/swirl-image-grid/swirl-image-grid.spec.tsx
Before:
https://github.com/user-attachments/assets/93d5a9a0-2cef-4adb-a91c-c3d7169569af
After:
https://github.com/user-attachments/assets/d6f69fff-fed2-4cf4-85b4-26e041e5cc7c
> Improve swirl-image-grid image load

- .changeset/rare-mice-shave.md
- packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.css
- packages/swirl-components/src/components/swirl-image-grid-item/swirl-image-grid-item.tsx
> Improve image grid background loading

- .changeset/lovely-taxis-shop.md
- packages/swirl-components/src/components/swirl-text-input/swirl-text-input.tsx
- [Ticket](https://linear.app/flip/issue/EMP-110/11413-dynamically-updating-content-not-announced-for-screen-reader)
> add aria-live to character counter

- .changeset/orange-crabs-beg.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-thumbnail/swirl-thumbnail.spec.tsx
- packages/swirl-components/src/components/swirl-thumbnail/swirl-thumbnail.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/ENG-1677/show-cropremove-buttons-on-hover-inline-media)
> Replace SwirlThumbnail removal button icon

- .changeset/plenty-toys-deliver.md
- packages/swirl-components/src/components/swirl-file-chip/swirl-file-chip.tsx
> Add preview and download part attributes to swirl-file-chip

- .changeset/cuddly-bananas-happen.md
- packages/swirl-components/src/components/swirl-action-list-item/swirl-action-list-item.css
- packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.css
- packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.css
- [Ticket](https://linear.app/flip/issue/EMP-139/247-aktuelle-position-des-fokus-deutlich-prioritat-hoch)
> Add focus outline to list items

- .changeset/dull-ways-check.md
- packages/swirl-components/src/components/swirl-file-chip/swirl-file-chip.spec.tsx
- packages/swirl-components/src/components/swirl-file-chip/swirl-file-chip.tsx
- packages/swirl-components/src/utils.ts
> Support document mime types in swirl-file-chip

- .changeset/four-planets-remember.md
- packages/swirl-components/src/components/swirl-file-chip/swirl-file-chip.css
> Improve file chip accessibility

- .changeset/thick-impalas-matter.md
- packages/swirl-components/src/components/swirl-file-viewer/swirl-file-viewer.spec.tsx
- packages/swirl-components/src/components/swirl-file-viewer/viewers/swirl-file-viewer-image/swirl-file-viewer-image.css
- packages/swirl-components/src/components/swirl-file-viewer/viewers/swirl-file-viewer-image/swirl-file-viewer-image.tsx
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.spec.tsx
- packages/swirl-components/src/components/swirl-lightbox/swirl-lightbox.tsx
- [ENG-1654](https://linear.app/flip/issue/ENG-1654/improve-close-when-clicking-outside-behavior-when-viewing-images)
**Issue 1**
The image was taking up the entire width of the container, which was preventing the clicks from being considerered as clicks on the backdrop.
**Issue 2**
The keyboard listener was not receiving any event when the user would have one of the arrow buttons focused, and that button would be disabled (because the user was on the first or last page).
Steps to reproduce:
1. Open the lightbox
2. Use the arrow button to navigate to page 2
3. Use the arrow button to navigate back to page 1
4. Pressing Esc
> Fix swirl-lightbox closing with backdrop click and Escape key

- .changeset/orange-students-kick.md
- packages/swirl-components/src/components/swirl-modal/swirl-modal.css
>  Fix swirl-modal styles in drawer variant

- .changeset/loud-cows-allow.md
- .changeset/red-schools-provide.md
- packages/swirl-components/src/components/swirl-form-control/swirl-form-control.spec.tsx
- packages/swirl-components/src/components/swirl-form-control/swirl-form-control.tsx
> Fix form control error aria live

- .changeset/brown-cups-cover.md
- packages/swirl-components/.storybook/preview.js
- packages/swirl-components/src/docs/01-usage/01-get-started.stories.mdx
> Fix defineCustomElements import in Storybook

- .changeset/tender-frogs-nail.md
- packages/swirl-components/src/components/swirl-popover/swirl-popover.spec.tsx
- packages/swirl-components/src/components/swirl-popover/swirl-popover.tsx
Due to security reasons, clicks on an iframe do not bubble to the parent window, the same seem to apply to focusin.
The popover needs to be extended support window blur into an iframe to handle close.
- [Ticket](#)
- [Design](#)
> Fix popover not closing when clicking on iframe

- .changeset/eighty-rats-judge.md
- packages/swirl-components/src/components/swirl-shell-navigation-item/swirl-shell-navigation-item.spec.tsx
- packages/swirl-components/src/components/swirl-shell-navigation-item/swirl-shell-navigation-item.tsx
> Add title attribute to swirl-shell-navigation-item

- .changeset/clever-tools-whisper.md
- packages/swirl-components/src/components/swirl-option-list-item/swirl-option-list-item.css
> Adjust swirl-option-list-item avatar slot

- .changeset/dirty-cameras-grow.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-avatar-group/swirl-avatar-group.css
- packages/swirl-components/src/components/swirl-avatar-group/swirl-avatar-group.spec.tsx
- packages/swirl-components/src/components/swirl-avatar-group/swirl-avatar-group.stories.ts
- packages/swirl-components/src/components/swirl-avatar-group/swirl-avatar-group.tsx
- packages/swirl-components/vscode-data.json
- [Ticket](https://linear.app/flip/issue/ENG-2334/flipweb-add-page-seen-button)
- [Design](https://www.figma.com/design/t6ISOeXcBoEErcolnLivai/Knowledge-Base?node-id=2491-35895&m=dev)
> feat(components): add support for 3+ avatars in avatar group

- .changeset/young-lobsters-deny.md
- packages/swirl-components/src/components/swirl-console-layout/swirl-console-layout.css
- packages/swirl-components/src/components/swirl-console-layout/swirl-console-layout.spec.tsx
- packages/swirl-components/src/components/swirl-console-layout/swirl-console-layout.tsx
> Act 1837 swirl show scrollbar only for content and prevent layout

- .changeset/funny-pans-sit.md
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.css
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.spec.tsx
- packages/swirl-components/src/components/swirl-app-bar/swirl-app-bar.tsx
> Show right controls in small viewports when heading is not present in swirl-app-bar

- .changeset/nervous-crabs-approve.md
- packages/swirl-components/src/components/swirl-console-layout/swirl-console-layout.css
> Act 1869 swirl fix console layout  content container height

- .changeset/famous-apes-beg.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.tsx
…source-list-item
- [Ticket](#)
- [Design](#)
> Change allowHtml default value to false in swirl-resource-list-item

- .changeset/breezy-deers-visit.md
- packages/swirl-components/src/components/swirl-file-chip/swirl-file-chip.tsx
- packages/swirl-components/src/components/swirl-file-viewer/swirl-file-viewer.tsx
- packages/swirl-components/src/utils.ts
- [Ticket](https://linear.app/flip/issue/ENG-2475/flip-web-upload-tiff-as-misc-file)
> Whitelist supported image types of SwirlFileViewer

- .changeset/empty-apples-bake.md
- packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.css
- [Ticket](https://linear.app/flip/issue/ENG-2499/flipweb-fix-animation-flicking-in-the-chat-list)
> Fix resource list item jitter

- .changeset/serious-numbers-fix.md
- packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.css
- packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.stories.ts
> Remove --swirl-ghost-button-background-default token override in swirl-resource-list-item

- .changeset/fair-ladybugs-learn.md
- apps/swirl-docs/public/robots.txt
Allow search engine indexing for getflip.dev
- [Ticket](#)
- [Design](#)
> Allow search engine indexing getflip.dev

- .changeset/hungry-rings-think.md
- packages/swirl-components/src/components/swirl-text/swirl-text.css
- packages/swirl-components/src/components/swirl-text/swirl-text.tsx
- packages/swirl-components/vscode-data.json
To accommodate the designs, the disabled color had to be added to SwirlText.
- [Ticket](#)
- [Design](#)
> Add disabled text color to SwirlText

- .changeset/smart-points-eat.md
- packages/swirl-components/src/components/swirl-resource-list-item/swirl-resource-list-item.css
> Fix background color in swirl-resource-list-item

- .changeset/metal-rats-drum.md
- packages/swirl-components/src/components/swirl-tag/swirl-tag.css
Makes all tag variants the same size by applying a transparent border; only applies a color on the "outline" variant.
- [Ticket](https://linear.app/flip/issue/DS-65/swirl-make-sure-that-all-variants-of-the-swirl-tag-have-the-same-size)
- [Design](#)
> Fix swirl-tag border sizing

- .changeset/serious-bears-shave.md
- packages/swirl-components/src/components.d.ts
- packages/swirl-components/src/components/swirl-resource-list-section/swirl-resource-list-section.tsx
- packages/swirl-components/src/components/swirl-separator/swirl-separator.spec.tsx
- packages/swirl-components/src/components/swirl-separator/swirl-separator.tsx
- packages/swirl-components/vscode-data.json
Add semantics to swirl separator and fix a11y issue on SwirlResourceListSection with separator.
Elements with `role=separator` are not allowed inside element with `role=list`. Given that SwirlSeparator needs to be set to `none` for certain usages to be merely illustrative and have not semantic meaning. 
- [Ticket](#)
- [Design](#)
> Add semantics to swirl separator

- .changeset/hip-rabbits-give.md
- apps/swirl-docs/src/components/CommandMenu/HitComponentFactory/IconHitsGenerator.tsx
> Getflipdev app is crashing when searching

- .changeset/modern-singers-watch.md
- packages/swirl-components/src/components/swirl-avatar/swirl-avatar.css
- packages/swirl-components/src/components/swirl-avatar/swirl-avatar.tsx
- packages/swirl-components/vscode-data.json
> Add neutral color to swirl-avatar
